import { Box, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

import { Inter } from "next/font/google";

import { Providers } from "./provider";

import Container from "./components/Container";
import SideBar from "./components/SideBar";

import "./globals.scss";

const inter = Inter({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MantineProvider>
            <Container>
              <Box className="flex bg-gray-100">
                <SideBar />

                {children}
              </Box>
            </Container>
          </MantineProvider>
        </Providers>
      </body>
    </html>
  );
}
